- name: Configure Apps
  hosts: localhost
  connection: local
  become: true
  tags:
      - apps
  roles:
      - role: apps

- name: Configure Otehrs
  hosts: localhost
  connection: local
  become: true
  roles:
      - role: kubernetes
      - role: sudo