---
- name: Ensure apps are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - git
    - vim
    - python3-pip
    - vlc
    - nfs-common
    - sublime-text
    - apt-transport-https
    - chrome-gnome-shell
    - bash-completion
    - gnupg
    - lsb-release
    - ca-certificates
    - openrazer-meta
    -

- name: Add aliases to ~/.bash_aliases
  blockinfile:
    path: "/home/{{ username }}/.bash_aliases"
    block: "{{ item.alias }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.marker }}"
  loop:
    - { alias: "alias k='kubectl'", marker: "kubectl" }
