---
- name: Ensure apps are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - git
    - vim
    - python3-pip
    - vlc
    - nfs-common
    - sublime-text
    - apt-transport-https
    - chrome-gnome-shell
    - bash-completion
    - gnupg
    - lsb-release
    - ca-certificates
    - openrazer-meta
    - sshpass

- name: KVM Pre-Reqs
  apt:
      name: "{{ item }}"
      state: present
  with_items:
      - bridge-utils
      - cpu-checker
      - libvirt-clients
      - libvirt-daemon
      - qemu
      - qemu-kvm

- name: Check if Virtualization Capabilities exist
  shell: kvm-ok
  register: kvm_status
  failed_when: '"KVM acceleration can NOT be used" in kvm_status.stdout'
  changed_when: false

- name: Ensure bash_aliases exists
  file:
    path: "/home/{{ username }}/.bash_aliases"
    state: exists