---
- name: Ensure apps are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - git
    - vim
    - python3-pip
    - vlc
    - nfs-common
    - sublime-text
    - apt-transport-https
    - chrome-gnome-shell
    - bash-completion
    - gnupg
    - lsb-release
    - ca-certificates
    - openrazer-meta
    -
