---
- hosts: localhost
  tasks:
    - stat:
        path: "{{ id_rsa_file }}"
      register: op

    - name: Generating ssh key pair
      command: ssh-keygen -t rsa -b 4096 -f "{{ id_rsa_file }}" -q -N "{{ local_key_passphrase }}"
      when: op.stat.exists == false

    - debug:
        msg: "Key pair already exists. Using the same key."
      when: op.stat.exists

    - name: Copy public key to the nodes
      command: sshpass -p "{{ item.password }}" ssh-copy-id -i "{{ id_rsa_file }}" {{ item.username }}@"{{ item.ip }}" -f -o StrictHostKeyChecking=no
      loop: "{{ nodes }}"

  vars_files:
    - vars/main.yaml
    - vars/secrets.yaml