---
- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  loop:
    - repo: ppa:lutris-team/lutris
      state: present
    - repo: ppa:damentz/liquorix
      state: present

- name: Ensure apps are installed
  apt:
    name:
        - curl
        - git
        - vim
        - python3-pip
        - vlc
        - nfs-common
        - apt-transport-https
        - chrome-gnome-shell
        - bash-completion
        - gnupg
        - lsb-release
        - ca-certificates
        - openrazer-meta
        - sshpass
        - lutris
        - wine64
        - "linux-image-liquorix-{{ system.architecture }}"
        - "linux-headers-liquorix-{{ system.architecture }}"
    state: present
    update_cache: true

- name: Ensure pip apps are installed
  pip:
    name:
      - kube-hunter

- name: KVM Pre-Reqs
  apt:
      name: "{{ item }}"
      state: present
  with_items:
      - bridge-utils
      - cpu-checker
      - libvirt-clients
      - libvirt-daemon
      - qemu
      - qemu-kvm

- name: Check if Virtualization Capabilities exist
  shell: kvm-ok
  register: kvm_status
  failed_when: '"KVM acceleration can NOT be used" in kvm_status.stdout'
  changed_when: false

- name: Ensure bash_aliases exists
  file:
    path: "/home/{{ local.username }}/.bash_aliases"
    state: touch